version: '3.1'

services:
#  auth:
#    build: .
#    ports:
#    - 3000:3000
#    - 9229:9229
#    command:
#      - node
#      - "--inspect-brk=0.0.0.0"
#      - "./bin/www"
#    depends_on:
#    - auth-db

  auth-db:
    image: postgres
    restart: always
    ports:
    - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: auth-db
