env:
  node: true
  commonjs: true
  es2021: true
  'cypress/globals': true
extends:
  - plugin:cypress/recommended
parserOptions:
  ecmaVersion: 12
rules: {
  'semi': ['error', 'never']
}
plugins: ['cypress']