env:
  node: true
  commonjs: true
  es2021: true
  'jest/globals': true
extends:
  - eslint:recommended
  - plugin:jest/all
parserOptions:
  ecmaVersion: 12
rules: {
  'semi': ['error', 'never']
}
plugins: ['pug', 'jest']